services:
  # Zabbix 6.0
  database-zabbix-60:
    image: postgres:14
    networks:
      - zabbix-60
    environment:
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_pwd"
      POSTGRES_DB: "zabbix"

  zabbix-server-pgsql-60:
    image: zabbix/zabbix-server-pgsql:alpine-6.0-latest
    networks:
      - zabbix-60
    environment:
      DB_SERVER_HOST: database-zabbix-60
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pwd
    depends_on:
      - "database-zabbix-60"

  zabbix-web-nginx-pgsql-60:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.0-latest
    ports:
      - "8086:8080"
    networks:
      - zabbix-60
    environment:
      ZBX_SERVER_HOST: zabbix-server-pgsql-60
      DB_SERVER_HOST: database-zabbix-60
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pwd
    depends_on:
      - "database-zabbix-60"
      - "zabbix-server-pgsql-60"

  # Zabbix 6.2
  database-zabbix-62:
    image: postgres:14
    networks:
      - zabbix-62
    environment:
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_pwd"
      POSTGRES_DB: "zabbix"

  zabbix-server-pgsql-62:
    image: zabbix/zabbix-server-pgsql:alpine-6.2-latest
    networks:
      - zabbix-62
    environment:
      DB_SERVER_HOST: database-zabbix-62
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pwd
    depends_on:
      - "database-zabbix-62"

  zabbix-web-nginx-pgsql-62:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.2-latest
    ports:
      - "8087:8080"
    networks:
      - zabbix-62
    environment:
      ZBX_SERVER_HOST: zabbix-server-pgsql-62
      DB_SERVER_HOST: database-zabbix-62
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pwd
    depends_on:
      - "database-zabbix-62"
      - "zabbix-server-pgsql-62"


  # Zabbix 6.4
  database-zabbix-64:
    image: postgres:14
    networks:
      - zabbix-64
    environment:
      POSTGRES_USER: "zabbix"
      POSTGRES_PASSWORD: "zabbix_pwd"
      POSTGRES_DB: "zabbix"

  zabbix-server-pgsql-64:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    networks:
      - zabbix-64
    environment:
      DB_SERVER_HOST: database-zabbix-64
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pwd
    depends_on:
      - "database-zabbix-64"

  zabbix-web-nginx-pgsql-64:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    ports:
      - "8088:8080"
    networks:
      - zabbix-64
    environment:
      ZBX_SERVER_HOST: zabbix-server-pgsql-64
      DB_SERVER_HOST: database-zabbix-64
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pwd
    depends_on:
      - "database-zabbix-64"
      - "zabbix-server-pgsql-64"


networks:
  zabbix-60: {}
  zabbix-62: {}
  zabbix-64: {}
